### ISSUE TITLE
Add a JSON Writing Mode

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-c#187]
It would be nice to have a JSON downgrade mode, similar to what we have in ion-java's [`withJsonDowngrade`](https://github.com/amzn/ion-java/blob/b6842d54245fdef9366236856130d9cb086b6f37/src/com/amazon/ion/system/IonTextWriterBuilder.java#L360-L381) mode.

**Comment by nirosys** [comment]
JSON downconversion was added with revision 1ed8f6c3369a23ec146378553af2251b9af2a4cd, closing.
