### ISSUE TITLE
Documentation for ion-c 404s

### ISSUE THREAD

**Issue by CapnRat** [amazon-ion/ion-c#313]
The documentation linked to from the [list of libraries for different languages](https://amazon-ion.github.io/ion-docs/libs.html) is currently hitting a 404 for ion-c. Not sure when this started, but it seems to have been that way for the past few weeks at least.

The last run of the "pages build and deployment" action seems to have succeeded and explicitly states that it has successfully deployed to the same url that is 404ing ( https://amzn.github.io/ion-c/ ). So sounds like something additional needs checking to validate a successful run of the action. https://github.com/amazon-ion/ion-c/actions/runs/3627999704

**Comment by nirosys** [comment]
Ah, thank you! We've recently started moving ion repos over to this (amazon-ion) org, and need to update that libraries link. The documentation should be accessible [here](https://amazon-ion.github.io/ion-c/). I'll get that link updated asap, thank you for bringing it to our attention.

**Comment by nirosys** [comment]
Links have been updated with amazon-ion/ion-docs#186. Thank you!
